apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::290958055480:user/cli-user
      username: cli-user
      groups:
        - system:masters
