apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 290958055480.dkr.ecr.ap-south-1.amazonaws.com/auth-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: JWT_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: JWT_SECRET_ACCESS_KEY
        - name: JWT_SECRET_REFRESH_KEY
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: JWT_SECRET_REFRESH_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: DATABASE_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: PORT
