apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-service
  labels:
    app: ai-assistant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-assistant-service
  template:
    metadata:
      labels:
        app: ai-assistant-service
    spec:
      containers:
      - name: ai-assistant-service
        image: 323690581774.dkr.ecr.us-east-1.amazonaws.com/ai-assistant-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-assistant-env
              key: OPENAI_API_KEY
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ai-assistant-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-assistant-config
              key: PORT
