apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-service
spec:
  selector:
    app: ai-assistant-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: LoadBalancer
