apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 290958055480.dkr.ecr.ap-south-1.amazonaws.com/user-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: JWT_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: user-env
              key: JWT_ACCESS_TOKEN_SECRET
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: user-env
              key: MONGO_URI
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: PORT
